name: Feature Release Workflow

on:
  push:
    branches:
      - 'feature/*'

jobs:
  feature_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Checkstyle Check
        run: mvn checkstyle:check

      - name: Build and Install
        run: mvn install

      - name: Extract branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
          
          # extract branch name on pull request
          - name: Print branch name
            if: github.event_name == 'pull_request'
            run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"

          # print branch name
          - name: Get branch name
            run: echo 'The branch name is' $BRANCH_NAME

      - name: Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Cloud - Update available list
          title: PR
          body: PR
          base: develop
          branch: $BRANCH_NAME
          delete-branch: true