name: Feature Release Workflow

on:
  push:
    branches:
      - 'feature/*'
permissions:
  contents: write
      
jobs:
  feature_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Checkstyle Check
        run: mvn checkstyle:check

      - name: Build and Install
        run: mvn install

      - name: Get Branch Name
        id: branch-base
        run: echo "A branch atual é ${GITHUB_REF#refs/heads/}"

      - name: Criar PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.branch-base.outputs.result }}
          base: develop
          title: Título do Pull Request
          body: Descrição do Pull Request
