name: Develop Branch Action

on:
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven and Run Checkstyle
        run: |
          mvn install
          mvn checkstyle:check

      - name: Determine Version Increment
        id: version
        run: |
          version=$(git log --format=%B -n 1 ${{ github.sha }} | grep -Eo '(MAJOR|MINOR)')
          echo "version=$version" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = "Develop branch changes";
            const body = "This pull request was automatically created by the Develop Branch Action.";
            const head = github.context.ref;
            const base = "release/v0.0.1"; // Update to your target branch
            const version = process.env.version || 'MINOR'; // Default to MINOR
            // Logic to increment version
            octokit.pulls.create({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              title,
              body,
              head,
              base
            });

      - name: Deploy to AWS
        # Add AWS deployment steps here
