name: Release Workflow

on:
  push:
    branches:
      - develop

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Checkstyle Check
        run: mvn checkstyle:check

      - name: Build and Install
        run: mvn install

      - name: Determine Next Release Version
        id: release_version
        run: |
          current_version=$(git describe --abbrev=0 --tags)
          version_parts=(${current_version//./ })
          next_patch=$((version_parts[2] + 1))
          next_version="${version_parts[0]}.${version_parts[1]}.$next_patch"
          echo "::set-output name=next_version::$next_version"

      - name: Check if release branch exists
        id: release_branch_exists
        run: |
          release_branch="release/v0.0.1"
          if git show-ref --quiet refs/heads/$release_branch; then
            echo "::set-output name=branch_exists::true"
          else
            echo "::set-output name=branch_exists::false"
          fi

      - name: Create Release Branch
        if: steps.release_branch_exists.outputs.branch_exists == 'false'
        run: |
          next_version=${{ steps.release_version.outputs.next_version }}
          release_branch="release/v$next_version"
          git checkout -b $release_branch
          git push origin $release_branch

      - name: Create Pull Request
        if: steps.release_branch_exists.outputs.branch_exists == 'false'
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: release/v${{ steps.release_version.outputs.next_version }}
          title: "Release v${{ steps.release_version.outputs.next_version }}"
          body: "Automated release for v${{ steps.release_version.outputs.next_version }}"
